import { readdirSync, readFileSync, statSync } from 'node:fs'
import { join, relative } from 'node:path'
import { describe, expect, it } from 'vitest'

// S-5: the translation template (translations/gnomeola.pot, generated by scripts/i18n-pot.ts with xgettext)
// must match the source: every message wrapped in _() / ngettext() is in it, and nothing stale is.
// Checked here without needing xgettext, by reading the string literals directly.

const PKG = join(import.meta.dirname, '..')
const SRC = join(PKG, 'src', 'renderer')
/** The shared data layer's strings (format, settings…) ship in this app's catalogue too. */
const CORE_SRC = join(PKG, '..', 'ui-core', 'src')

function files(dir: string, acc: string[] = []): string[] {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e)
    if (statSync(p).isDirectory()) files(p, acc)
    else if (/\.tsx?$/.test(e) && !e.endsWith('.d.ts')) acc.push(p)
  }
  return acc
}

const unquote = (q: string, body: string) =>
  body.replace(/\\(.)/g, (_m, c: string) => (c === 'n' ? '\n' : c === q ? q : c === '\\' ? '\\' : `\\${c}`))

/** Messages in the source: literal first arguments of _() and both forms of ngettext(). */
function sourceMessages(): { messages: Set<string>; nonLiteral: string[] } {
  const messages = new Set<string>()
  const nonLiteral: string[] = []
  for (const f of [...files(SRC), ...files(CORE_SRC)]) {
    if (f.includes(`${join('src', 'i18n')}`)) continue
    const text = readFileSync(f, 'utf8')
    for (const m of text.matchAll(/(?<![\w.$])_\(\s*(['"])((?:\\.|(?!\1)[^\\])*)\1\s*[,)]/g)) {
      messages.add(unquote(m[1]!, m[2]!))
    }
    for (const m of text.matchAll(
      /(?<![\w.$])ngettext\(\s*(['"])((?:\\.|(?!\1)[^\\])*)\1\s*,\s*(['"])((?:\\.|(?!\3)[^\\])*)\3/g,
    )) {
      messages.add(unquote(m[1]!, m[2]!))
      messages.add(unquote(m[3]!, m[4]!))
    }
    // a call whose argument is not a string literal cannot be extracted (and so never translated)
    for (const m of text.matchAll(/(?<![\w.$])_\(\s*([^'"\s)])/g)) {
      nonLiteral.push(`${relative(PKG, f)}: _(${m[1]}…`)
    }
  }
  return { messages, nonLiteral }
}

/** msgid / msgid_plural strings in a .pot, with continuation lines joined. */
function potMessages(pot: string): Set<string> {
  const out = new Set<string>()
  let cur: string[] | null = null
  const flush = () => {
    if (cur) {
      const s = cur.join('')
      if (s) out.add(s)
    }
    cur = null
  }
  for (const line of pot.split('\n')) {
    const start = /^msgid(?:_plural)? "(.*)"$/.exec(line)
    const cont = /^"(.*)"$/.exec(line)
    if (start) {
      flush()
      cur = [start[1]!]
    } else if (cont && cur) cur.push(cont[1]!)
    else flush()
  }
  flush()
  return new Set([...out].map((s) => unquote('"', s)))
}

describe('translation template', () => {
  const src = sourceMessages()
  const pot = potMessages(readFileSync(join(PKG, 'translations', 'gnomeola.pot'), 'utf8'))

  it('finds the messages at all (the scanner works)', () => {
    expect(src.messages.size).toBeGreaterThan(100)
    expect(src.messages).toContain('Jump to Live')
    expect(src.messages).toContain('A speech model is not downloaded yet, so recording can’t transcribe')
  })

  it('wraps only literals, so every message can be extracted', () => {
    expect(src.nonLiteral).toEqual([])
  })

  it('has every source message, and nothing stale (run `pnpm --filter @gnomeola/desktop i18n:pot`)', () => {
    const missing = [...src.messages].filter((m) => !pot.has(m))
    const stale = [...pot].filter((m) => !src.messages.has(m))
    expect({ missing, stale }).toEqual({ missing: [], stale: [] })
  })
})
