// Generate brand/tokens/tokens.css and brand/tokens/tailwind.css from brand/tokens/tokens.json.
//
//   node brand/scripts/tokens.ts            write the CSS
//   node brand/scripts/tokens.ts --check    exit 1 if the CSS is stale
//
// tokens.json is W3C Design Tokens. A group named after a mode (light, dark, light-high-contrast,
// dark-high-contrast) is dropped from the variable name and its tokens land in that mode's CSS block, so
// `color.dark.bg.window` becomes `--k-color-bg-window` under the dark selectors.
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

export const MODES = ['light', 'dark', 'light-high-contrast', 'dark-high-contrast'] as const
export type Mode = (typeof MODES)[number]

type Dimension = { value: number; unit: string }
type ShadowLayer = {
  color: string
  offsetX: Dimension
  offsetY: Dimension
  blur: Dimension
  spread: Dimension
}
type Typography = {
  fontFamily: string
  fontSize: Dimension
  lineHeight: Dimension
  fontWeight: number
  letterSpacing: Dimension
}
export type Token = {
  $type: string
  $value: unknown
  $description?: string
  $extensions?: Record<string, unknown>
}
export type Tree = { [key: string]: Tree | Token | string }

/** A token with its path, the path with mode groups removed, and the mode it belongs to (base if none). */
export type Flat = { path: string[]; name: string[]; mode: Mode | 'base'; token: Token }

const isToken = (v: unknown): v is Token => typeof v === 'object' && v !== null && '$value' in v

export function flatten(tree: Tree, path: string[] = [], out: Flat[] = []): Flat[] {
  for (const [key, value] of Object.entries(tree)) {
    if (key.startsWith('$')) continue
    const p = [...path, key]
    if (isToken(value)) {
      const mode = p.find((s): s is Mode => (MODES as readonly string[]).includes(s)) ?? 'base'
      out.push({ path: p, name: p.filter((s) => s !== mode || mode === 'base'), mode, token: value })
    } else if (typeof value === 'object') flatten(value, p, out)
  }
  return out
}

/** Follows `{a.b.c}` aliases to a concrete value. */
export function resolve(tree: Tree, value: unknown, seen: string[] = []): unknown {
  if (typeof value !== 'string' || !/^\{[^}]+\}$/.test(value)) return value
  const ref = value.slice(1, -1)
  if (seen.includes(ref)) throw new Error(`alias cycle: ${[...seen, ref].join(' -> ')}`)
  let node: Tree | Token | string | undefined = tree
  for (const seg of ref.split('.')) node = typeof node === 'object' && !isToken(node) ? node[seg] : undefined
  if (!isToken(node)) throw new Error(`unresolved alias ${value}`)
  return resolve(tree, node.$value, [...seen, ref])
}

const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()
export const varName = (name: string[]) => `--k-${name.map(kebab).join('-')}`
const dim = (d: Dimension) => `${d.value}${d.unit}`
const family = (f: string[]) => f.map((x) => (/\s/.test(x) ? `"${x}"` : x)).join(', ')

/** CSS declarations for one token (typography expands to several custom properties). */
export function declarations(tree: Tree, f: Flat): [string, string][] {
  const v = resolve(tree, f.token.$value)
  const n = varName(f.name)
  switch (f.token.$type) {
    case 'color':
      return [[n, (v as string).toLowerCase()]]
    case 'dimension':
      return [[n, dim(v as Dimension)]]
    case 'duration':
      return [[n, dim(v as Dimension)]]
    case 'number':
      // the only number token is the icon tile radius fraction
      return [[n, `${(v as number) * 100}%`]]
    case 'cubicBezier':
      return [[n, `cubic-bezier(${(v as number[]).join(', ')})`]]
    case 'fontFamily':
      return [[n, family(v as string[])]]
    case 'shadow':
      return [
        [
          n,
          (v as ShadowLayer[])
            .map((l) => `${dim(l.offsetX)} ${dim(l.offsetY)} ${dim(l.blur)} ${dim(l.spread)} ${l.color}`)
            .join(', '),
        ],
      ]
    case 'typography': {
      const t = v as Typography
      const fam = String(t.fontFamily).slice(1, -1).split('.').map(kebab).join('-')
      const extra = (f.token.$extensions?.kacola ?? {}) as Record<string, string>
      const out: [string, string][] = [
        [`${n}-family`, `var(--k-${fam})`],
        [`${n}-size`, dim(t.fontSize)],
        [`${n}-line-height`, dim(t.lineHeight)],
        [`${n}-weight`, String(t.fontWeight)],
        [`${n}-tracking`, dim(t.letterSpacing)],
      ]
      if (extra.fontStyle) out.push([`${n}-style`, extra.fontStyle])
      if (extra.textTransform) out.push([`${n}-transform`, extra.textTransform])
      return out
    }
    default:
      throw new Error(`unsupported $type ${f.token.$type} at ${f.path.join('.')}`)
  }
}

const HEADER =
  '/* Generated by brand/scripts/tokens.ts from brand/tokens/tokens.json — do not edit by hand. */\n'

function block(selector: string, decls: [string, string][], indent = ''): string {
  const body = decls.map(([k, v]) => `${indent}  ${k}: ${v};`).join('\n')
  return `${indent}${selector} {\n${body}\n${indent}}\n`
}

export function tokensCss(tree: Tree): string {
  const flat = flatten(tree)
  const by = (mode: Mode | 'base') =>
    flat.filter((f) => f.mode === mode).flatMap((f) => declarations(tree, f))
  const [base, light, dark, lightHc, darkHc] = [
    by('base'),
    by('light'),
    by('dark'),
    by('light-high-contrast'),
    by('dark-high-contrast'),
  ]
  const scheme = (s: string): [string, string] => ['color-scheme', s]
  const osDark = ':root:not([data-theme="light"])'
  const parts = [
    HEADER,
    block(':root', base),
    block(':root,\n[data-theme="light"]', [scheme('light'), ...light]),
    block('[data-theme="dark"]', [scheme('dark'), ...dark]),
    `@media (prefers-color-scheme: dark) {\n${block(osDark, [scheme('dark'), ...dark], '  ')}}\n`,
    // high contrast: explicit attribute, or the OS preference unless the page opts out with data-contrast=normal
    block('[data-contrast="high"],\n[data-contrast="high"] [data-theme="light"]', lightHc),
    block('[data-theme="dark"][data-contrast="high"],\n[data-contrast="high"] [data-theme="dark"]', darkHc),
    `@media (prefers-color-scheme: dark) {\n${block(`${osDark}[data-contrast="high"]`, darkHc, '  ')}}\n`,
    `@media (prefers-contrast: more) {\n${block(':root:not([data-contrast="normal"])', lightHc, '  ')}\n${block(
      ':root[data-theme="dark"]:not([data-contrast="normal"])',
      darkHc,
      '  ',
    )}}\n`,
    `@media (prefers-contrast: more) and (prefers-color-scheme: dark) {\n${block(
      `${osDark}:not([data-contrast="normal"])`,
      darkHc,
      '  ',
    )}}\n`,
    `@media (prefers-reduced-motion: reduce) {\n${block(
      ':root',
      flat.filter((f) => f.token.$type === 'duration').map((f): [string, string] => [varName(f.name), '0ms']),
      '  ',
    )}}\n`,
    '@keyframes k-record-pulse {\n  from {\n    transform: scale(1);\n    opacity: 0.55;\n  }\n  to {\n    transform: scale(1.9);\n    opacity: 0;\n  }\n}\n',
  ]
  return parts.join('\n')
}

/** Tailwind v4 theme: utilities reference the custom properties, so theme and contrast switching just work. */
export function tailwindCss(tree: Tree): string {
  const flat = flatten(tree)
  const t: [string, string][] = []
  for (const f of flat.filter((x) => x.mode === 'light' && x.token.$type === 'color')) {
    const n = f.name.slice(1).map(kebab).join('-')
    t.push([`--color-${n}`, `var(${varName(f.name)})`])
  }
  for (const f of flat.filter((x) => x.path[0] === 'font'))
    t.push([`--font-${f.name[2]}`, `var(${varName(f.name)})`])
  const types = flat.filter((x) => x.token.$type === 'typography')
  for (const f of types) {
    const n = kebab(f.name[1]!)
    const v = varName(f.name)
    t.push(
      [`--text-${n}`, `var(${v}-size)`],
      [`--text-${n}--line-height`, `var(${v}-line-height)`],
      [`--text-${n}--letter-spacing`, `var(${v}-tracking)`],
      [`--text-${n}--font-weight`, `var(${v}-weight)`],
    )
  }
  for (const f of flat.filter((x) => x.path[0] === 'radius'))
    t.push([`--radius-${f.name[1]}`, `var(${varName(f.name)})`])
  for (const f of flat.filter((x) => x.path[0] === 'shadow' && x.mode === 'light'))
    t.push([`--shadow-${f.name[1]}`, `var(${varName(f.name)})`])
  for (const f of flat.filter((x) => x.path[0] === 'easing'))
    t.push([`--ease-${kebab(f.name[1]!)}`, `var(${varName(f.name)})`])
  t.push(
    ['--spacing', '4px'],
    ['--animate-record-pulse', 'k-record-pulse var(--k-duration-pulse) var(--k-easing-in-out) infinite'],
  )

  const utilities = types.map((f) => {
    const v = varName(f.name)
    const extra = (f.token.$extensions?.kacola ?? {}) as Record<string, string>
    const decls: [string, string][] = [
      ['font-family', `var(${v}-family)`],
      ['font-size', `var(${v}-size)`],
      ['line-height', `var(${v}-line-height)`],
      ['font-weight', `var(${v}-weight)`],
      ['letter-spacing', `var(${v}-tracking)`],
    ]
    if (extra.fontStyle) decls.push(['font-style', `var(${v}-style)`])
    if (extra.textTransform) decls.push(['text-transform', `var(${v}-transform)`])
    if (extra.fontVariantNumeric) decls.push(['font-variant-numeric', extra.fontVariantNumeric])
    return block(`@utility type-${kebab(f.name[1]!)}`, decls)
  })
  return [
    HEADER,
    '/* Import after tokens.css and tailwindcss. Spacing follows the 4px grid: p-3 = 12px, gap-4 = 16px. */\n',
    block('@theme inline', t),
    ...utilities,
  ].join('\n')
}

if (import.meta.main) {
  const dir = join(import.meta.dirname, '..', 'tokens')
  const tree = JSON.parse(readFileSync(join(dir, 'tokens.json'), 'utf8')) as Tree
  const outputs = { 'tokens.css': tokensCss(tree), 'tailwind.css': tailwindCss(tree) }
  const check = process.argv.includes('--check')
  let stale = false
  for (const [file, text] of Object.entries(outputs)) {
    const path = join(dir, file)
    if (check) {
      if (readFileSync(path, 'utf8') !== text) {
        console.error(`✗ brand/tokens/${file} is stale — run: pnpm brand:tokens`)
        stale = true
      }
    } else writeFileSync(path, text)
  }
  if (stale) process.exit(1)
  console.log(check ? '✓ brand tokens current' : `wrote ${Object.keys(outputs).join(', ')}`)
}
