// Keeps the Shell extension's embedded copy of the D-Bus contract identical to the canonical XML.
//
//   node scripts/extension-dbus.ts          rewrite extensions/<uuid>/dbus.js from the XML
//   node scripts/extension-dbus.ts --check  exit 1 if the copy has drifted (also a unit test)
//
// The extension cannot read the XML at runtime (it is not installed with the daemon's files, and the
// extension zip must be self-contained), hence a generated module rather than a symlink.
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = join(import.meta.dirname, '..')
export const XML_PATH = join(ROOT, 'packages', 'daemon', 'dbus', 'com.kacperlubisz.Kacola.xml')
export const DBUS_JS_PATH = join(ROOT, 'extensions', 'kacola@kacperlubisz.com', 'dbus.js')

export function renderDbusJs(xml: string): string {
  if (xml.includes('`') || xml.includes('${') || xml.includes('\\'))
    throw new Error('the interface XML cannot be embedded in a template literal as-is')
  return `// GENERATED by scripts/extension-dbus.ts from packages/daemon/dbus/com.kacperlubisz.Kacola.xml — do not edit.
// The D-Bus contract, embedded verbatim so the extension zip is self-contained; a unit test fails if this
// copy drifts from the canonical file.

export const BUS_NAME = 'com.kacperlubisz.Kacola'
export const OBJECT_PATH = '/com/kacperlubisz/Kacola'
export const INTERFACE_NAME = 'com.kacperlubisz.Kacola'

export const INTERFACE_XML = \`${xml}\`
`
}

if (import.meta.main) {
  const want = renderDbusJs(readFileSync(XML_PATH, 'utf8'))
  if (process.argv.includes('--check')) {
    if (readFileSync(DBUS_JS_PATH, 'utf8') !== want) {
      process.stderr.write(`${DBUS_JS_PATH} is out of date: run node scripts/extension-dbus.ts\n`)
      process.exit(1)
    }
  } else {
    writeFileSync(DBUS_JS_PATH, want)
  }
}
