// S-4 — generate THIRD_PARTY_NOTICES.md from the real production dependency tree, and fail on any licence
// that is not known to be compatible with distributing gnomeola under GPL-3.0-or-later.
//
//   node scripts/third-party-notices.ts            write THIRD_PARTY_NOTICES.md
//   node scripts/third-party-notices.ts --check    exit 1 if the file is stale or a licence is not allowed
//
// Models and voices are data, not npm packages: they are listed from an explicit, reviewed table below
// (kept next to the catalog that downloads them), because their licences are what actually constrains
// redistribution and pnpm cannot see them.
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

export type Pkg = { name: string; versions: string[]; license: string; homepage?: string; author?: string }

/** SPDX ids we have reviewed as compatible with shipping inside a GPL-3.0-or-later application. */
export const ALLOWED = new Set([
  'MIT',
  'MIT-0',
  'ISC',
  'BSD-2-Clause',
  'BSD-3-Clause',
  'Apache-2.0',
  'MPL-2.0',
  'Unlicense',
  '0BSD',
  'CC0-1.0',
  'BlueOak-1.0.0',
  'Python-2.0',
  'LGPL-2.1-or-later',
  'LGPL-3.0-or-later',
  'GPL-3.0-or-later',
])

/** Accepts `A OR B` if any alternative is allowed; `A AND B` only if all are. Parentheses are stripped. */
export function licenceAllowed(expr: string): boolean {
  const e = expr.replace(/[()]/g, '').trim()
  if (/\sOR\s/.test(e)) return e.split(/\s+OR\s+/).some(licenceAllowed)
  if (/\sAND\s/.test(e)) return e.split(/\s+AND\s+/).every(licenceAllowed)
  return ALLOWED.has(e)
}

/** Reviewed data dependencies (models, voices, fixtures). Extended as work streams land. */
export const DATA: { name: string; licence: string; source: string; note: string }[] = []

export function collect(root: string): Pkg[] {
  const out = execFileSync('pnpm', ['licenses', 'list', '--prod', '--json'], { cwd: root, encoding: 'utf8' })
  const groups = JSON.parse(out) as Record<string, Pkg[]>
  return Object.values(groups)
    .flat()
    .filter((p) => !p.name.startsWith('@gnomeola/'))
    .sort((a, b) => a.name.localeCompare(b.name))
}

export function render(pkgs: Pkg[]): string {
  const lines = [
    '# Third-party notices',
    '',
    'gnomeola is distributed under GPL-3.0-or-later. It includes or downloads the following third-party',
    'components. This file is generated by `scripts/third-party-notices.ts` from the production dependency',
    'tree; do not edit it by hand.',
    '',
    '## Software',
    '',
    '| package | version | licence | homepage |',
    '| --- | --- | --- | --- |',
    ...pkgs.map((p) => `| ${p.name} | ${p.versions.join(', ')} | ${p.license} | ${p.homepage ?? ''} |`),
    '',
    '## Models, voices and data',
    '',
  ]
  if (!DATA.length) lines.push('_None yet._', '')
  else {
    lines.push('| component | licence | source | note |', '| --- | --- | --- | --- |')
    for (const d of DATA) lines.push(`| ${d.name} | ${d.licence} | ${d.source} | ${d.note} |`)
    lines.push('')
  }
  lines.push(
    '## Inspiration',
    '',
    'gnomeola is an independent, clean-room project inspired by [Granola](https://www.granola.ai/). It contains no',
    'Granola code, assets or branding and is not affiliated with or endorsed by Granola.',
    '',
  )
  return lines.join('\n')
}

if (import.meta.main) {
  const root = join(import.meta.dirname, '..')
  const pkgs = collect(root)
  const bad = pkgs.filter((p) => !licenceAllowed(p.license))
  for (const d of DATA)
    if (!licenceAllowed(d.licence)) bad.push({ name: d.name, versions: [], license: d.licence })
  if (bad.length) {
    console.error('✗ licences not on the reviewed allow-list:')
    for (const b of bad) console.error(`  ${b.name}: ${b.license}`)
    process.exit(1)
  }
  const file = join(root, 'THIRD_PARTY_NOTICES.md')
  const next = render(pkgs)
  if (process.argv.includes('--check')) {
    const current = existsSync(file) ? readFileSync(file, 'utf8') : ''
    if (current !== next) {
      console.error('✗ THIRD_PARTY_NOTICES.md is stale — run: node scripts/third-party-notices.ts')
      process.exit(1)
    }
    console.log(`✓ notices current; ${pkgs.length} packages, all licences allowed`)
  } else {
    writeFileSync(file, next)
    console.log(`wrote THIRD_PARTY_NOTICES.md (${pkgs.length} packages, ${DATA.length} data components)`)
  }
}
